sonar.projectKey=aptlogica_sereni-jwt-provider_e93385ef-3917-48bf-b724-ca96963f99ce

sonar.language=go
sonar.sources=.
sonar.tests=tests
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.exclusions=Dockerfile,coverage.html,**/*_test.go
sonar.scm.exclusions.disabled=true
