name: Feature request
description: Suggest an idea for this project
labels: enhancement
body:
  - type: markdown
    attributes:
      value: "## Feature description"
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the feature.
      required: true